# Generated by Django 5.1 on 2024-08-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
